"""bd_unlocker_rest_get_request — auto-generated tool for GET /request.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: unlocker-rest-api
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "unlocker_rest"
WRITES = False


async def bd_unlocker_rest_get_request(zone: str, url: str, format: str, method: str | None = None, country: str | None = None, data_format: str | None = None) -> dict[str, Any]:
    """Call GET /request.

    From: GET /request
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: unlocker-rest-api

    Args:
            zone: Zone identifier that defines your Bright Data product configuration. Find your zones at: https://brightdata.com/cp/zones
            url: Complete target URL to scrape. Must include protocol (http/https). Example: `https://geo.brdtest.com/mygeo.json`
            format: Format for requesting a raw HTML via proxy is `raw`.  Format for request a JSON response is `json`.
            method: Method for requesting an HTML via proxy is `GET`.
            country: Country code of proxy which request is relayed through.
            data_format: Additional response format: `markdown` converts HTML to markdown, `screenshot` returns PNG image of the page

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/request"
    params: dict[str, Any] = {}
    params["zone"] = zone
    params["url"] = url
    params["format"] = format
    if method is not None:
        params["method"] = method
    if country is not None:
        params["country"] = country
    if data_format is not None:
        params["data_format"] = data_format
    return await bd_request("GET", path, params=params)
