"""proxy_manager group — auto-generated tool registrations.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Hand-written smoke tools (with `# SMOKE-TOOL: hand-written` marker) are preserved.
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import TYPE_CHECKING

from .bd_proxy_manager_get_domain_metrics import bd_proxy_manager_get_domain_metrics

if TYPE_CHECKING:
    from fastmcp import FastMCP


def register_tools(mcp: FastMCP) -> None:
    """Register all proxy_manager tools with the FastMCP instance."""
    mcp.tool()(bd_proxy_manager_get_domain_metrics)


__all__ = [
    "bd_proxy_manager_get_domain_metrics",
    "register_tools",
]
