"""bd_proxy_manager_get_domain_metrics — auto-generated tool for GET /domains/{metric}.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: proxy-manager
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "proxy_manager"
WRITES = False


async def bd_proxy_manager_get_domain_metrics(metric: str, from_arg: str, to: str, zones: str | None = None) -> dict[str, Any]:
    """Domain usage metrics

    Returns domain usage metrics from Bright Data. Supported metrics: bw (Bandwidth
    consumption), req (Request count).

    From: GET /domains/{metric}
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: proxy-manager

    Args:
            metric: Metric type to query: #### Available Metrics  - `/bw` - Bandwidth consumption  - `/req` - Request count
            from_arg: Start date (YYYY-MM-DD)
            to: End date (YYYY-MM-DD)
            zones: Zone name filter. Omit to include all zones.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = f"/domains/{metric}"
    params: dict[str, Any] = {}
    params["from"] = from_arg
    params["to"] = to
    if zones is not None:
        params["zones"] = zones
    return await bd_request("GET", path, params=params)
