"""video_downloader group — auto-generated tool registrations.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Hand-written smoke tools (with `# SMOKE-TOOL: hand-written` marker) are preserved.
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import TYPE_CHECKING

from .bd_video_downloader_trigger_video_download import bd_video_downloader_trigger_video_download

if TYPE_CHECKING:
    from fastmcp import FastMCP


def register_tools(mcp: FastMCP) -> None:
    """Register all video_downloader tools with the FastMCP instance."""
    mcp.tool()(bd_video_downloader_trigger_video_download)


__all__ = [
    "bd_video_downloader_trigger_video_download",
    "register_tools",
]
