"""bd_video_downloader_trigger_video_download — auto-generated tool for POST /dca/trigger_hp.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: video-downloader
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request
from lib.safety import requires_write_enabled

GROUP = "video_downloader"
WRITES = True


@requires_write_enabled
async def bd_video_downloader_trigger_video_download(
    collector: str, body: dict[str, Any] | None = None
) -> dict[str, Any]:
    """Trigger a video download job

    Submits one or more video download jobs. Results are delivered to your configured
    storage destination when each job completes. > **Access required:** The Video Downloader
    API is not enabled by default. Contact
    [support@brightdata.com](mailto:support@brightdata.com) to enable it for your account. >
    **Delivery required:** A delivery destination must be configured before sending
    requests. See [Delivery options](https://docs.brightdata.com/datasets/scrapers/scrapers-
    library/delivery-options#delivery-options).

    From: POST /dca/trigger_hp
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: video-downloader

    Args:
            collector: Your Video Downloader collector ID. This is a fixed value assigned when the feature is enabled on your account.
            body: JSON request body. See BD docs for schema.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/dca/trigger_hp"
    params: dict[str, Any] = {}
    params["collector"] = collector
    return await bd_request("POST", path, params=params, json=body)
