"""scraper_studio group — auto-generated tool registrations.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Hand-written smoke tools (with `# SMOKE-TOOL: hand-written` marker) are preserved.
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import TYPE_CHECKING

from .bd_scraper_studio_create_dca_collector import bd_scraper_studio_create_dca_collector
from .bd_scraper_studio_create_dca_collectors_by_collector_id_automate_template import bd_scraper_studio_create_dca_collectors_by_collector_id_automate_template
from .bd_scraper_studio_create_dca_collectors_by_collector_id_refactor_template import bd_scraper_studio_create_dca_collectors_by_collector_id_refactor_template
from .bd_scraper_studio_create_dca_crawl import bd_scraper_studio_create_dca_crawl
from .bd_scraper_studio_create_dca_trigger import bd_scraper_studio_create_dca_trigger
from .bd_scraper_studio_create_dca_trigger_hp import bd_scraper_studio_create_dca_trigger_hp
from .bd_scraper_studio_create_dca_trigger_immediate import bd_scraper_studio_create_dca_trigger_immediate
from .bd_scraper_studio_get_dca_collectors_by_collector_id_automate_template_progress import bd_scraper_studio_get_dca_collectors_by_collector_id_automate_template_progress
from .bd_scraper_studio_get_dca_collectors_by_collector_id_refactor_template_progress import bd_scraper_studio_get_dca_collectors_by_collector_id_refactor_template_progress
from .bd_scraper_studio_get_dca_dataset import bd_scraper_studio_get_dca_dataset
from .bd_scraper_studio_get_dca_get_result import bd_scraper_studio_get_dca_get_result
from .bd_scraper_studio_get_dca_jobs_by_job_id_hp_errors import bd_scraper_studio_get_dca_jobs_by_job_id_hp_errors
from .bd_scraper_studio_get_dca_log_by_job_id import bd_scraper_studio_get_dca_log_by_job_id

if TYPE_CHECKING:
    from fastmcp import FastMCP


def register_tools(mcp: FastMCP) -> None:
    """Register all scraper_studio tools with the FastMCP instance."""
    mcp.tool()(bd_scraper_studio_create_dca_collector)
    mcp.tool()(bd_scraper_studio_create_dca_collectors_by_collector_id_automate_template)
    mcp.tool()(bd_scraper_studio_create_dca_collectors_by_collector_id_refactor_template)
    mcp.tool()(bd_scraper_studio_create_dca_crawl)
    mcp.tool()(bd_scraper_studio_create_dca_trigger)
    mcp.tool()(bd_scraper_studio_create_dca_trigger_hp)
    mcp.tool()(bd_scraper_studio_create_dca_trigger_immediate)
    mcp.tool()(bd_scraper_studio_get_dca_collectors_by_collector_id_automate_template_progress)
    mcp.tool()(bd_scraper_studio_get_dca_collectors_by_collector_id_refactor_template_progress)
    mcp.tool()(bd_scraper_studio_get_dca_dataset)
    mcp.tool()(bd_scraper_studio_get_dca_get_result)
    mcp.tool()(bd_scraper_studio_get_dca_jobs_by_job_id_hp_errors)
    mcp.tool()(bd_scraper_studio_get_dca_log_by_job_id)


__all__ = [
    "bd_scraper_studio_create_dca_collector",
    "bd_scraper_studio_create_dca_collectors_by_collector_id_automate_template",
    "bd_scraper_studio_create_dca_collectors_by_collector_id_refactor_template",
    "bd_scraper_studio_create_dca_crawl",
    "bd_scraper_studio_create_dca_trigger",
    "bd_scraper_studio_create_dca_trigger_hp",
    "bd_scraper_studio_create_dca_trigger_immediate",
    "bd_scraper_studio_get_dca_collectors_by_collector_id_automate_template_progress",
    "bd_scraper_studio_get_dca_collectors_by_collector_id_refactor_template_progress",
    "bd_scraper_studio_get_dca_dataset",
    "bd_scraper_studio_get_dca_get_result",
    "bd_scraper_studio_get_dca_jobs_by_job_id_hp_errors",
    "bd_scraper_studio_get_dca_log_by_job_id",
    "register_tools",
]
