"""bd_scraper_studio_create_dca_collectors_by_collector_id_automate_template — auto-generated tool for POST /dca/collectors/{collector_id}/automate_template.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: web-scraper-ide-rest-api
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request
from lib.safety import requires_write_enabled

GROUP = "scraper_studio"
WRITES = True


@requires_write_enabled
async def bd_scraper_studio_create_dca_collectors_by_collector_id_automate_template(collector_id: str, body: dict[str, Any] | None = None) -> dict[str, Any]:
    """Trigger AI Flow

    Triggers AI flow to generate working scraper code.

    From: POST /dca/collectors/{collector_id}/automate_template
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: web-scraper-ide-rest-api

    Args:
            collector_id: Collector ID returned by the [Create Scraper Template](/api-reference/scraper-studio-api/ai-flow/create-scraper-template) API endpoint.
            body: JSON request body. See BD docs for schema.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = f"/dca/collectors/{collector_id}/automate_template"
    return await bd_request("POST", path, json=body)
