"""bd_scraper_studio_create_dca_trigger_hp — auto-generated tool for POST /dca/trigger_hp.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: web-scraper-ide-rest-api
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request
from lib.safety import requires_write_enabled

GROUP = "scraper_studio"
WRITES = True


@requires_write_enabled
async def bd_scraper_studio_create_dca_trigger_hp(
    collector: str, body: dict[str, Any] | None = None
) -> dict[str, Any]:
    """Trigger a scraper for batch collection method

    Triggers an HP batch scraper job and returns a job ID that can be used to track
    execution status and retrieve errors.

    From: POST /dca/trigger_hp
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: web-scraper-ide-rest-api

    Args:
            collector: A unique identification of scraper
            body: JSON request body. See BD docs for schema.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/dca/trigger_hp"
    params: dict[str, Any] = {}
    params["collector"] = collector
    return await bd_request("POST", path, params=params, json=body)
