"""bd_scraper_studio_create_dca_crawl — auto-generated tool for POST /dca/crawl.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: web-scraper-ide-rest-api
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request
from lib.safety import requires_write_enabled

GROUP = "scraper_studio"
WRITES = True


@requires_write_enabled
async def bd_scraper_studio_create_dca_crawl(
    collector: str,
    timeout: str,
    version: str | None = None,
    name: str | None = None,
    body: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Trigger a scraper for batch collection method

    From: POST /dca/crawl
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: web-scraper-ide-rest-api

    Args:
            collector: A unique identification of scraper
            timeout: Request timeout duration. Must be between 25s and 50s.
            version: Set to `dev` to trigger the development version of the scraper
            name: `human_name` - A human readable name for the batch
            body: JSON request body. See BD docs for schema.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/dca/crawl"
    params: dict[str, Any] = {}
    params["collector"] = collector
    params["timeout"] = timeout
    if version is not None:
        params["version"] = version
    if name is not None:
        params["name"] = name
    return await bd_request("POST", path, params=params, json=body)
