"""bd_scraper_studio_get_dca_log_by_job_id — auto-generated tool for GET /dca/log/{job_id}.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: web-scraper-ide-rest-api
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "scraper_studio"
WRITES = False


async def bd_scraper_studio_get_dca_log_by_job_id(job_id: str) -> dict[str, Any]:
    """Get job data by job ID

    From: GET /dca/log/{job_id}
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: web-scraper-ide-rest-api

    Args:
            job_id: The ID of the job to retrieve.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = f"/dca/log/{job_id}"
    return await bd_request("GET", path)
