"""bd_scraper_studio_create_dca_collector — auto-generated tool for POST /dca/collector.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: web-scraper-ide-rest-api
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request
from lib.safety import requires_write_enabled

GROUP = "scraper_studio"
WRITES = True


@requires_write_enabled
async def bd_scraper_studio_create_dca_collector(body: dict[str, Any] | None = None) -> dict[str, Any]:
    """Create Scraper Template

    Creates a Scraper Studio scraper with a sample template.

    From: POST /dca/collector
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: web-scraper-ide-rest-api

    Args:
            body: JSON request body. See BD docs for schema.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/dca/collector"
    return await bd_request("POST", path, json=body)
