"""bd_scraper_studio_get_dca_collectors_by_collector_id_refactor_template_progress — auto-generated tool for GET /dca/collectors/{collector_id}/refactor_template/progress.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: web-scraper-ide-rest-api
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "scraper_studio"
WRITES = False


async def bd_scraper_studio_get_dca_collectors_by_collector_id_refactor_template_progress(collector_id: str) -> dict[str, Any]:
    """Get Self-Healing Job Progress

    From: GET /dca/collectors/{collector_id}/refactor_template/progress
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: web-scraper-ide-rest-api

    Args:
            collector_id: Collector ID returned by the [Create Scraper Template](/api-reference/scraper-studio-api/ai-flow/create-scraper-template) API endpoint.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = f"/dca/collectors/{collector_id}/refactor_template/progress"
    return await bd_request("GET", path)
