"""bd_scraper_studio_get_dca_jobs_by_job_id_hp_errors — auto-generated tool for GET /dca/jobs/{job_id}/hp_errors.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: web-scraper-ide-rest-api
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "scraper_studio"
WRITES = False


async def bd_scraper_studio_get_dca_jobs_by_job_id_hp_errors(
    job_id: str, skip_normalize: bool | None = None
) -> dict[str, Any]:
    """Get errors for an job

    Retrieves a list of errors generated during execution of an batch scraper job. The job
    ID must be obtained from the `/trigger_hp` endpoint. If the `skip_normalize` query
    parameter is provided, full (non-normalized) error details are returned.

    From: GET /dca/jobs/{job_id}/hp_errors
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: web-scraper-ide-rest-api

    Args:
            job_id: Job ID returned from the `/trigger_hp` endpoint
            skip_normalize: Return full (non-normalized) error details

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = f"/dca/jobs/{job_id}/hp_errors"
    params: dict[str, Any] = {}
    if skip_normalize is not None:
        params["skip_normalize"] = skip_normalize
    return await bd_request("GET", path, params=params)
