"""bd_scraper_studio_create_dca_trigger — auto-generated tool for POST /dca/trigger.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: web-scraper-ide-rest-api
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request
from lib.safety import requires_write_enabled

GROUP = "scraper_studio"
WRITES = True


@requires_write_enabled
async def bd_scraper_studio_create_dca_trigger(
    collector: str,
    version: str | None = None,
    name: str | None = None,
    queue_next: int | None = None,
    queue: str | None = None,
    confirm_cancel: int | None = None,
    no_downloads: int | None = None,
    deadline: str | None = None,
    body: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Trigger a scraper for batch collection method

    From: POST /dca/trigger
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: web-scraper-ide-rest-api

    Args:
            collector: A unique identification of scraper
            version: Set to `dev` to trigger the development version of the scraper
            name: `human_name` - A human readable name for the batch
            queue_next: If there's already something in the crawl queue, push this job into the queue
            queue: Send another batch of requests that will start after the last one is finished
            confirm_cancel: Cancel running job and run instead, submit the request and cancel running one
            no_downloads: Disable media file download
            deadline: Set job time deadline, job will be terminated after specified time. `h` for hours, `m` for minutes, `s` for seconds.
            body: JSON request body. See BD docs for schema.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/dca/trigger"
    params: dict[str, Any] = {}
    params["collector"] = collector
    if version is not None:
        params["version"] = version
    if name is not None:
        params["name"] = name
    if queue_next is not None:
        params["queue_next"] = queue_next
    if queue is not None:
        params["queue"] = queue
    if confirm_cancel is not None:
        params["confirm_cancel"] = confirm_cancel
    if no_downloads is not None:
        params["no_downloads"] = no_downloads
    if deadline is not None:
        params["deadline"] = deadline
    return await bd_request("POST", path, params=params, json=body)
