"""scrapers group — auto-generated tool registrations.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Hand-written smoke tools (with `# SMOKE-TOOL: hand-written` marker) are preserved.
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import TYPE_CHECKING

from .bd_scrapers_create_datasets_v3_trigger import bd_scrapers_create_datasets_v3_trigger
from .bd_scrapers_get_datasets_v3_progress_by_snapshot_id import bd_scrapers_get_datasets_v3_progress_by_snapshot_id
from .bd_scrapers_get_datasets_v3_snapshot_by_snapshot_id import bd_scrapers_get_datasets_v3_snapshot_by_snapshot_id

if TYPE_CHECKING:
    from fastmcp import FastMCP


def register_tools(mcp: FastMCP) -> None:
    """Register all scrapers tools with the FastMCP instance."""
    mcp.tool()(bd_scrapers_create_datasets_v3_trigger)
    mcp.tool()(bd_scrapers_get_datasets_v3_progress_by_snapshot_id)
    mcp.tool()(bd_scrapers_get_datasets_v3_snapshot_by_snapshot_id)


__all__ = [
    "bd_scrapers_create_datasets_v3_trigger",
    "bd_scrapers_get_datasets_v3_progress_by_snapshot_id",
    "bd_scrapers_get_datasets_v3_snapshot_by_snapshot_id",
    "register_tools",
]
