"""archive group — auto-generated tool registrations.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Hand-written smoke tools (with `# SMOKE-TOOL: hand-written` marker) are preserved.
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import TYPE_CHECKING

from .bd_archive_create_webarchive_dump import bd_archive_create_webarchive_dump
from .bd_archive_create_webarchive_search import bd_archive_create_webarchive_search
from .bd_archive_get_webarchive_dump_by_dump_id import bd_archive_get_webarchive_dump_by_dump_id
from .bd_archive_get_webarchive_search_by_search_id import (
    bd_archive_get_webarchive_search_by_search_id,
)
from .bd_archive_list_webarchive_dumps import bd_archive_list_webarchive_dumps
from .bd_archive_list_webarchive_searches import bd_archive_list_webarchive_searches

if TYPE_CHECKING:
    from fastmcp import FastMCP


def register_tools(mcp: FastMCP) -> None:
    """Register all archive tools with the FastMCP instance."""
    mcp.tool()(bd_archive_create_webarchive_dump)
    mcp.tool()(bd_archive_create_webarchive_search)
    mcp.tool()(bd_archive_get_webarchive_dump_by_dump_id)
    mcp.tool()(bd_archive_get_webarchive_search_by_search_id)
    mcp.tool()(bd_archive_list_webarchive_dumps)
    mcp.tool()(bd_archive_list_webarchive_searches)


__all__ = [
    "bd_archive_create_webarchive_dump",
    "bd_archive_create_webarchive_search",
    "bd_archive_get_webarchive_dump_by_dump_id",
    "bd_archive_get_webarchive_search_by_search_id",
    "bd_archive_list_webarchive_dumps",
    "bd_archive_list_webarchive_searches",
    "register_tools",
]
