"""bd_archive_get_webarchive_search_by_search_id — auto-generated tool for GET /webarchive/search/{search_id}.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: web-archive-api
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "archive"
WRITES = False


async def bd_archive_get_webarchive_search_by_search_id(search_id: str) -> dict[str, Any]:
    """Get search status

    Check the status and results of a previously submitted web archive search query.

    From: GET /webarchive/search/{search_id}
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: web-archive-api

    Args:
            search_id: Unique identifier for the search

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = f"/webarchive/search/{search_id}"
    return await bd_request("GET", path)
