"""bd_archive_create_webarchive_dump — auto-generated tool for POST /webarchive/dump.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: web-archive-api
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request
from lib.safety import requires_write_enabled

GROUP = "archive"
WRITES = True


@requires_write_enabled
async def bd_archive_create_webarchive_dump(body: dict[str, Any] | None = None) -> dict[str, Any]:
    """Deliver a snapshot to Amazon S3, Azure Blob Storage or a Webhook

    Delivers a snapshot from a completed search to cloud storage using the specified
    delivery strategy.

    From: POST /webarchive/dump
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: web-archive-api

    Args:
            body: JSON request body. See BD docs for schema.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/webarchive/dump"
    return await bd_request("POST", path, json=body)
