"""bd_archive_create_webarchive_search — auto-generated tool for POST /webarchive/search.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: web-archive-api
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request
from lib.safety import requires_write_enabled

GROUP = "archive"
WRITES = True


@requires_write_enabled
async def bd_archive_create_webarchive_search(body: dict[str, Any] | None = None) -> dict[str, Any]:
    """Run a search

    To initiate a search of our Archive, use the following `/search` endpoint.

    From: POST /webarchive/search
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: web-archive-api

    Args:
            body: JSON request body. See BD docs for schema.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/webarchive/search"
    return await bd_request("POST", path, json=body)
