"""bd_archive_get_webarchive_dump_by_dump_id — auto-generated tool for GET /webarchive/dump/{dump_id}.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: web-archive-api
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "archive"
WRITES = False


async def bd_archive_get_webarchive_dump_by_dump_id(dump_id: str) -> dict[str, Any]:
    """Get data snapshot (dump) status

    Check the status and progress of a specific data snapshot (dump) using the `dump_id`.

    From: GET /webarchive/dump/{dump_id}
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: web-archive-api

    Args:
            dump_id: Unique identifier for the data snapshot (dump)

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = f"/webarchive/dump/{dump_id}"
    return await bd_request("GET", path)
