"""bd_archive_list_webarchive_dumps — auto-generated tool for GET /webarchive/dumps.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: web-archive-api
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "archive"
WRITES = False


async def bd_archive_list_webarchive_dumps() -> dict[str, Any]:
    """Get all data snapshot statuses

    Retrieve the status and metadata of all data snapshots (dumps).

    From: GET /webarchive/dumps
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: web-archive-api

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/webarchive/dumps"
    return await bd_request("GET", path)
