"""bd_archive_list_webarchive_searches — auto-generated tool for GET /webarchive/searches.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: web-archive-api
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "archive"
WRITES = False


async def bd_archive_list_webarchive_searches() -> dict[str, Any]:
    """Get all search statuses

    Retrieve the status and metadata of all current web archive searches.

    From: GET /webarchive/searches
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: web-archive-api

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/webarchive/searches"
    return await bd_request("GET", path)
