"""misc group — auto-generated tool registrations.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Hand-written smoke tools (with `# SMOKE-TOOL: hand-written` marker) are preserved.
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import TYPE_CHECKING

from .bd_misc_create_datasets_filter import bd_misc_create_datasets_filter
from .bd_misc_create_datasets_v3_scrape import bd_misc_create_datasets_v3_scrape
from .bd_misc_create_serp_req import bd_misc_create_serp_req
from .bd_misc_create_unblocker_req import bd_misc_create_unblocker_req
from .bd_misc_get_serp_get_result import bd_misc_get_serp_get_result
from .bd_misc_get_unblocker_get_result import bd_misc_get_unblocker_get_result

if TYPE_CHECKING:
    from fastmcp import FastMCP


def register_tools(mcp: FastMCP) -> None:
    """Register all misc tools with the FastMCP instance."""
    mcp.tool()(bd_misc_create_datasets_filter)
    mcp.tool()(bd_misc_create_datasets_v3_scrape)
    mcp.tool()(bd_misc_create_serp_req)
    mcp.tool()(bd_misc_create_unblocker_req)
    mcp.tool()(bd_misc_get_serp_get_result)
    mcp.tool()(bd_misc_get_unblocker_get_result)


__all__ = [
    "bd_misc_create_datasets_filter",
    "bd_misc_create_datasets_v3_scrape",
    "bd_misc_create_serp_req",
    "bd_misc_create_unblocker_req",
    "bd_misc_get_serp_get_result",
    "bd_misc_get_unblocker_get_result",
    "register_tools",
]
