"""bd_misc_create_serp_req — auto-generated tool for POST /serp/req.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: async-api-reference,dca-custom-inputs,filter-csv-json
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request
from lib.safety import requires_write_enabled

GROUP = "misc"
WRITES = True


@requires_write_enabled
async def bd_misc_create_serp_req(zone: str, customer: str | None = None, body: dict[str, Any] | None = None) -> dict[str, Any]:
    """Call POST /serp/req.

    From: POST /serp/req
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: async-api-reference,dca-custom-inputs,filter-csv-json

    Args:
            zone: The name of your Bright Data Unlocker zone.
            customer: Your Bright Data account ID.
            body: JSON request body. See BD docs for schema.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/serp/req"
    params: dict[str, Any] = {}
    params["zone"] = zone
    if customer is not None:
        params["customer"] = customer
    return await bd_request("POST", path, params=params, json=body)
