"""bd_proxy_get_request — auto-generated tool for GET /request.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: proxy-rest-api
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "proxy"
WRITES = False


async def bd_proxy_get_request(
    zone: str,
    url: str,
    format: str,
    method: str | None = None,
    country: str | None = None,
    city: str | None = None,
    zip: str | None = None,
    asn: str | None = None,
    carrier: str | None = None,
    os: str | None = None,
    dns: str | None = None,
    session: str | None = None,
    ip: str | None = None,
    gip: str | None = None,
    c_tag: str | None = None,
    direct: bool | None = None,
) -> dict[str, Any]:
    """Call GET /request.

    From: GET /request
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: proxy-rest-api

    Args:
            zone: Name of the proxy zone which will service your request.
            url: Target URL for your request.
            format: Format for requesting a raw HTML via proxy is `raw`.  Format for request a JSON response is `json`.
            method: Method for requesting an HTML via proxy is `GET`.
            country: Country code of proxy which request is relayed through.
            city: City name of proxy which request is relayed through, must have country defined.  Supported in DC & ISP for zones pre-configured with cities, and in Residential and mobile networks by default.
            zip: Zip code which request is relayed through, must have country defined.  Supported in Residential networks only.
            asn: ASN code which request is relayed thru, must have country defined.  Supported in Residential networks only.
            carrier: For mobile network only: carrier code in which request is relayed through.  Supported in mobile networks only.
            os: Operating system of the client to set on proxy.  Supported in Residential and Mobile networks only.
            dns: Use `local` or `remote` to set if domain name mapping is done locally on client side or on remote proxy peer.
            session: A string relayed by the client to mark a session, all requests with the same session parameter will be relayed to the same proxy peer.
            ip: In Datacenter and ISP zones: Relay the request to a specific proxy identified by the `ip`.
            gip: In `Residential` and `Mobile` zones: Relay the request to a specific proxy group identified by the `gip`.
            c_tag: Include a unique `c_tag` flag in their requests. In response, businesses echo back the same tag in the header. This seamless exchange ensures that each response is bound to its corresponding request, eliminating confusion and streamlining data management.
            direct: Setting the parameter to `true` will instruct to process the request by Bright Data super proxy, a datacenter located proxy and not the proxy peer itself.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/request"
    params: dict[str, Any] = {}
    params["zone"] = zone
    params["url"] = url
    params["format"] = format
    if method is not None:
        params["method"] = method
    if country is not None:
        params["country"] = country
    if city is not None:
        params["city"] = city
    if zip is not None:
        params["zip"] = zip
    if asn is not None:
        params["ASN"] = asn
    if carrier is not None:
        params["carrier"] = carrier
    if os is not None:
        params["os"] = os
    if dns is not None:
        params["dns"] = dns
    if session is not None:
        params["session"] = session
    if ip is not None:
        params["ip"] = ip
    if gip is not None:
        params["gip"] = gip
    if c_tag is not None:
        params["c_tag"] = c_tag
    if direct is not None:
        params["direct"] = direct
    return await bd_request("GET", path, params=params)
