"""bd_proxy_get_response — auto-generated tool for GET /response.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: proxy-rest-api
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "proxy"
WRITES = False


async def bd_proxy_get_response(response_id: str) -> dict[str, Any]:
    """Call GET /response.

    From: GET /response
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: proxy-rest-api

    Args:
            response_id: Response ID

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/response"
    params: dict[str, Any] = {}
    params["response_id"] = response_id
    return await bd_request("GET", path, params=params)
