"""bd_proxy_create_request — auto-generated tool for POST /request.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: proxy-rest-api
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request
from lib.safety import requires_write_enabled

GROUP = "proxy"
WRITES = True


@requires_write_enabled
async def bd_proxy_create_request(body: dict[str, Any] | None = None) -> dict[str, Any]:
    """Call POST /request.

    From: POST /request
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: proxy-rest-api

    Args:
            body: JSON request body. See BD docs for schema.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/request"
    return await bd_request("POST", path, json=body)
