"""account_management group — auto-generated tool registrations.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Hand-written smoke tools (with `# SMOKE-TOOL: hand-written` marker) are preserved.
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import TYPE_CHECKING

from .bd_account_get_balance import bd_account_get_balance
from .bd_account_get_status import bd_account_get_status
from .bd_account_management_create_api_by_partner_name_signup_dedicated_dc import (
    bd_account_management_create_api_by_partner_name_signup_dedicated_dc,
)
from .bd_account_management_create_api_by_partner_name_signup_dedicated_isp import (
    bd_account_management_create_api_by_partner_name_signup_dedicated_isp,
)
from .bd_account_management_create_api_by_partner_name_signup_residential import (
    bd_account_management_create_api_by_partner_name_signup_residential,
)
from .bd_account_management_create_api_by_partner_name_signup_shared_dc import (
    bd_account_management_create_api_by_partner_name_signup_shared_dc,
)
from .bd_account_management_create_api_by_partner_name_signup_shared_isp import (
    bd_account_management_create_api_by_partner_name_signup_shared_isp,
)
from .bd_account_management_create_api_by_partner_name_signup_smart_resi import (
    bd_account_management_create_api_by_partner_name_signup_smart_resi,
)
from .bd_account_management_create_api_by_partner_name_usage_webhook import (
    bd_account_management_create_api_by_partner_name_usage_webhook,
)
from .bd_account_management_create_zone import bd_account_management_create_zone
from .bd_account_management_create_zone_add_password import (
    bd_account_management_create_zone_add_password,
)
from .bd_account_management_create_zone_blacklist import bd_account_management_create_zone_blacklist
from .bd_account_management_create_zone_change_disable import (
    bd_account_management_create_zone_change_disable,
)
from .bd_account_management_create_zone_domain_perm import (
    bd_account_management_create_zone_domain_perm,
)
from .bd_account_management_create_zone_ips import bd_account_management_create_zone_ips
from .bd_account_management_create_zone_ips_migrate import (
    bd_account_management_create_zone_ips_migrate,
)
from .bd_account_management_create_zone_ips_refresh import (
    bd_account_management_create_zone_ips_refresh,
)
from .bd_account_management_create_zone_remove_password import (
    bd_account_management_create_zone_remove_password,
)
from .bd_account_management_create_zone_switch_100uptime import (
    bd_account_management_create_zone_switch_100uptime,
)
from .bd_account_management_create_zone_whitelist import bd_account_management_create_zone_whitelist
from .bd_account_management_delete_api_by_partner_name_ips import (
    bd_account_management_delete_api_by_partner_name_ips,
)
from .bd_account_management_delete_zone import bd_account_management_delete_zone
from .bd_account_management_delete_zone_blacklist import bd_account_management_delete_zone_blacklist
from .bd_account_management_delete_zone_domain_perm import (
    bd_account_management_delete_zone_domain_perm,
)
from .bd_account_management_delete_zone_ips import bd_account_management_delete_zone_ips
from .bd_account_management_delete_zone_vips import bd_account_management_delete_zone_vips
from .bd_account_management_delete_zone_whitelist import bd_account_management_delete_zone_whitelist
from .bd_account_management_get_api_by_partner_name_carrier_ips_count import (
    bd_account_management_get_api_by_partner_name_carrier_ips_count,
)
from .bd_account_management_get_api_by_partner_name_carriers import (
    bd_account_management_get_api_by_partner_name_carriers,
)
from .bd_account_management_get_api_by_partner_name_countries import (
    bd_account_management_get_api_by_partner_name_countries,
)
from .bd_account_management_get_api_by_partner_name_customers import (
    bd_account_management_get_api_by_partner_name_customers,
)
from .bd_account_management_get_api_by_partner_name_get_asn import (
    bd_account_management_get_api_by_partner_name_get_asn,
)
from .bd_account_management_get_api_by_partner_name_ips import (
    bd_account_management_get_api_by_partner_name_ips,
)
from .bd_account_management_get_api_by_partner_name_proxies import (
    bd_account_management_get_api_by_partner_name_proxies,
)
from .bd_account_management_get_api_by_partner_name_shared_isp import (
    bd_account_management_get_api_by_partner_name_shared_isp,
)
from .bd_account_management_get_api_by_partner_name_socks5_proxies import (
    bd_account_management_get_api_by_partner_name_socks5_proxies,
)
from .bd_account_management_get_api_by_partner_name_usage_limit import (
    bd_account_management_get_api_by_partner_name_usage_limit,
)
from .bd_account_management_get_api_by_partner_name_usage_limit_stats import (
    bd_account_management_get_api_by_partner_name_usage_limit_stats,
)
from .bd_account_management_get_api_by_partner_name_usage_webhook import (
    bd_account_management_get_api_by_partner_name_usage_webhook,
)
from .bd_account_management_get_customer_balance import bd_account_management_get_customer_balance
from .bd_account_management_get_customer_bw import bd_account_management_get_customer_bw
from .bd_account_management_get_network_status_by_network_type import (
    bd_account_management_get_network_status_by_network_type,
)
from .bd_account_management_get_zone import bd_account_management_get_zone
from .bd_account_management_get_zone_blacklist import bd_account_management_get_zone_blacklist
from .bd_account_management_get_zone_bw import bd_account_management_get_zone_bw
from .bd_account_management_get_zone_cost import bd_account_management_get_zone_cost
from .bd_account_management_get_zone_ips_unavailable import (
    bd_account_management_get_zone_ips_unavailable,
)
from .bd_account_management_get_zone_proxies_pending_replacement import (
    bd_account_management_get_zone_proxies_pending_replacement,
)
from .bd_account_management_get_zone_whitelist import bd_account_management_get_zone_whitelist
from .bd_account_management_list_all_available_countries_per_zone_type import (
    bd_account_management_list_all_available_countries_per_zone_type,
)
from .bd_account_management_list_cities import bd_account_management_list_cities
from .bd_account_management_list_status import bd_account_management_list_status
from .bd_account_management_list_zone_count_available_ips import (
    bd_account_management_list_zone_count_available_ips,
)
from .bd_account_management_list_zone_get_active_zones import (
    bd_account_management_list_zone_get_active_zones,
)
from .bd_account_management_list_zone_get_all_zones import (
    bd_account_management_list_zone_get_all_zones,
)
from .bd_account_management_list_zone_ips import bd_account_management_list_zone_ips
from .bd_account_management_list_zone_passwords import bd_account_management_list_zone_passwords
from .bd_account_management_list_zone_permissions import bd_account_management_list_zone_permissions
from .bd_account_management_list_zone_recent_ips import bd_account_management_list_zone_recent_ips
from .bd_account_management_list_zone_route_ips import bd_account_management_list_zone_route_ips
from .bd_account_management_list_zone_route_vips import bd_account_management_list_zone_route_vips
from .bd_account_management_list_zone_static_cities import (
    bd_account_management_list_zone_static_cities,
)
from .bd_account_management_list_zone_status import bd_account_management_list_zone_status
from .bd_account_management_update_api_by_partner_name_disable_customer import (
    bd_account_management_update_api_by_partner_name_disable_customer,
)
from .bd_account_management_update_api_by_partner_name_enable_customer import (
    bd_account_management_update_api_by_partner_name_enable_customer,
)
from .bd_account_management_update_api_by_partner_name_ips import (
    bd_account_management_update_api_by_partner_name_ips,
)
from .bd_account_management_update_api_by_partner_name_refresh_ips import (
    bd_account_management_update_api_by_partner_name_refresh_ips,
)
from .bd_account_management_update_api_by_partner_name_usage_limit import (
    bd_account_management_update_api_by_partner_name_usage_limit,
)
from .bd_account_management_update_status import bd_account_management_update_status
from .bd_zones_list import bd_zones_list

if TYPE_CHECKING:
    from fastmcp import FastMCP


def register_tools(mcp: FastMCP) -> None:
    """Register all account_management tools with the FastMCP instance."""
    mcp.tool()(bd_account_get_balance)
    mcp.tool()(bd_account_get_status)
    mcp.tool()(bd_account_management_create_api_by_partner_name_signup_dedicated_dc)
    mcp.tool()(bd_account_management_create_api_by_partner_name_signup_dedicated_isp)
    mcp.tool()(bd_account_management_create_api_by_partner_name_signup_residential)
    mcp.tool()(bd_account_management_create_api_by_partner_name_signup_shared_dc)
    mcp.tool()(bd_account_management_create_api_by_partner_name_signup_shared_isp)
    mcp.tool()(bd_account_management_create_api_by_partner_name_signup_smart_resi)
    mcp.tool()(bd_account_management_create_api_by_partner_name_usage_webhook)
    mcp.tool()(bd_account_management_create_zone)
    mcp.tool()(bd_account_management_create_zone_add_password)
    mcp.tool()(bd_account_management_create_zone_blacklist)
    mcp.tool()(bd_account_management_create_zone_change_disable)
    mcp.tool()(bd_account_management_create_zone_domain_perm)
    mcp.tool()(bd_account_management_create_zone_ips)
    mcp.tool()(bd_account_management_create_zone_ips_migrate)
    mcp.tool()(bd_account_management_create_zone_ips_refresh)
    mcp.tool()(bd_account_management_create_zone_remove_password)
    mcp.tool()(bd_account_management_create_zone_switch_100uptime)
    mcp.tool()(bd_account_management_create_zone_whitelist)
    mcp.tool()(bd_account_management_delete_api_by_partner_name_ips)
    mcp.tool()(bd_account_management_delete_zone)
    mcp.tool()(bd_account_management_delete_zone_blacklist)
    mcp.tool()(bd_account_management_delete_zone_domain_perm)
    mcp.tool()(bd_account_management_delete_zone_ips)
    mcp.tool()(bd_account_management_delete_zone_vips)
    mcp.tool()(bd_account_management_delete_zone_whitelist)
    mcp.tool()(bd_account_management_get_api_by_partner_name_carrier_ips_count)
    mcp.tool()(bd_account_management_get_api_by_partner_name_carriers)
    mcp.tool()(bd_account_management_get_api_by_partner_name_countries)
    mcp.tool()(bd_account_management_get_api_by_partner_name_customers)
    mcp.tool()(bd_account_management_get_api_by_partner_name_get_asn)
    mcp.tool()(bd_account_management_get_api_by_partner_name_ips)
    mcp.tool()(bd_account_management_get_api_by_partner_name_proxies)
    mcp.tool()(bd_account_management_get_api_by_partner_name_shared_isp)
    mcp.tool()(bd_account_management_get_api_by_partner_name_socks5_proxies)
    mcp.tool()(bd_account_management_get_api_by_partner_name_usage_limit)
    mcp.tool()(bd_account_management_get_api_by_partner_name_usage_limit_stats)
    mcp.tool()(bd_account_management_get_api_by_partner_name_usage_webhook)
    mcp.tool()(bd_account_management_get_customer_balance)
    mcp.tool()(bd_account_management_get_customer_bw)
    mcp.tool()(bd_account_management_get_network_status_by_network_type)
    mcp.tool()(bd_account_management_get_zone)
    mcp.tool()(bd_account_management_get_zone_blacklist)
    mcp.tool()(bd_account_management_get_zone_bw)
    mcp.tool()(bd_account_management_get_zone_cost)
    mcp.tool()(bd_account_management_get_zone_ips_unavailable)
    mcp.tool()(bd_account_management_get_zone_proxies_pending_replacement)
    mcp.tool()(bd_account_management_get_zone_whitelist)
    mcp.tool()(bd_account_management_list_all_available_countries_per_zone_type)
    mcp.tool()(bd_account_management_list_cities)
    mcp.tool()(bd_account_management_list_status)
    mcp.tool()(bd_account_management_list_zone_count_available_ips)
    mcp.tool()(bd_account_management_list_zone_get_active_zones)
    mcp.tool()(bd_account_management_list_zone_get_all_zones)
    mcp.tool()(bd_account_management_list_zone_ips)
    mcp.tool()(bd_account_management_list_zone_passwords)
    mcp.tool()(bd_account_management_list_zone_permissions)
    mcp.tool()(bd_account_management_list_zone_recent_ips)
    mcp.tool()(bd_account_management_list_zone_route_ips)
    mcp.tool()(bd_account_management_list_zone_route_vips)
    mcp.tool()(bd_account_management_list_zone_static_cities)
    mcp.tool()(bd_account_management_list_zone_status)
    mcp.tool()(bd_account_management_update_api_by_partner_name_disable_customer)
    mcp.tool()(bd_account_management_update_api_by_partner_name_enable_customer)
    mcp.tool()(bd_account_management_update_api_by_partner_name_ips)
    mcp.tool()(bd_account_management_update_api_by_partner_name_refresh_ips)
    mcp.tool()(bd_account_management_update_api_by_partner_name_usage_limit)
    mcp.tool()(bd_account_management_update_status)
    mcp.tool()(bd_zones_list)


__all__ = [
    "bd_account_get_balance",
    "bd_account_get_status",
    "bd_account_management_create_api_by_partner_name_signup_dedicated_dc",
    "bd_account_management_create_api_by_partner_name_signup_dedicated_isp",
    "bd_account_management_create_api_by_partner_name_signup_residential",
    "bd_account_management_create_api_by_partner_name_signup_shared_dc",
    "bd_account_management_create_api_by_partner_name_signup_shared_isp",
    "bd_account_management_create_api_by_partner_name_signup_smart_resi",
    "bd_account_management_create_api_by_partner_name_usage_webhook",
    "bd_account_management_create_zone",
    "bd_account_management_create_zone_add_password",
    "bd_account_management_create_zone_blacklist",
    "bd_account_management_create_zone_change_disable",
    "bd_account_management_create_zone_domain_perm",
    "bd_account_management_create_zone_ips",
    "bd_account_management_create_zone_ips_migrate",
    "bd_account_management_create_zone_ips_refresh",
    "bd_account_management_create_zone_remove_password",
    "bd_account_management_create_zone_switch_100uptime",
    "bd_account_management_create_zone_whitelist",
    "bd_account_management_delete_api_by_partner_name_ips",
    "bd_account_management_delete_zone",
    "bd_account_management_delete_zone_blacklist",
    "bd_account_management_delete_zone_domain_perm",
    "bd_account_management_delete_zone_ips",
    "bd_account_management_delete_zone_vips",
    "bd_account_management_delete_zone_whitelist",
    "bd_account_management_get_api_by_partner_name_carrier_ips_count",
    "bd_account_management_get_api_by_partner_name_carriers",
    "bd_account_management_get_api_by_partner_name_countries",
    "bd_account_management_get_api_by_partner_name_customers",
    "bd_account_management_get_api_by_partner_name_get_asn",
    "bd_account_management_get_api_by_partner_name_ips",
    "bd_account_management_get_api_by_partner_name_proxies",
    "bd_account_management_get_api_by_partner_name_shared_isp",
    "bd_account_management_get_api_by_partner_name_socks5_proxies",
    "bd_account_management_get_api_by_partner_name_usage_limit",
    "bd_account_management_get_api_by_partner_name_usage_limit_stats",
    "bd_account_management_get_api_by_partner_name_usage_webhook",
    "bd_account_management_get_customer_balance",
    "bd_account_management_get_customer_bw",
    "bd_account_management_get_network_status_by_network_type",
    "bd_account_management_get_zone",
    "bd_account_management_get_zone_blacklist",
    "bd_account_management_get_zone_bw",
    "bd_account_management_get_zone_cost",
    "bd_account_management_get_zone_ips_unavailable",
    "bd_account_management_get_zone_proxies_pending_replacement",
    "bd_account_management_get_zone_whitelist",
    "bd_account_management_list_all_available_countries_per_zone_type",
    "bd_account_management_list_cities",
    "bd_account_management_list_status",
    "bd_account_management_list_zone_count_available_ips",
    "bd_account_management_list_zone_get_active_zones",
    "bd_account_management_list_zone_get_all_zones",
    "bd_account_management_list_zone_ips",
    "bd_account_management_list_zone_passwords",
    "bd_account_management_list_zone_permissions",
    "bd_account_management_list_zone_recent_ips",
    "bd_account_management_list_zone_route_ips",
    "bd_account_management_list_zone_route_vips",
    "bd_account_management_list_zone_static_cities",
    "bd_account_management_list_zone_status",
    "bd_account_management_update_api_by_partner_name_disable_customer",
    "bd_account_management_update_api_by_partner_name_enable_customer",
    "bd_account_management_update_api_by_partner_name_ips",
    "bd_account_management_update_api_by_partner_name_refresh_ips",
    "bd_account_management_update_api_by_partner_name_usage_limit",
    "bd_account_management_update_status",
    "bd_zones_list",
    "register_tools",
]
