"""bd_account_management_get_network_status_by_network_type — auto-generated tool for GET /network_status/{NETWORK_TYPE}.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: openapi,openapi-reseller
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "account_management"
WRITES = False


async def bd_account_management_get_network_status_by_network_type(network_type: str) -> dict[str, Any]:
    """Call GET /network_status/{NETWORK_TYPE}.

    From: GET /network_status/{NETWORK_TYPE}
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: openapi,openapi-reseller

    Args:
            network_type: Can be one of following:    `all`: All network type    `res`: Residential    `dc`: Datacenter     `mobile`: Mobile

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = f"/network_status/{network_type}"
    return await bd_request("GET", path)
