"""bd_account_management_list_zone_static_cities — auto-generated tool for GET /zone/static/cities.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: openapi,openapi-reseller
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "account_management"
WRITES = False


async def bd_account_management_list_zone_static_cities(country: str, pool_ip_type: str | None = None) -> dict[str, Any]:
    """Get list of available cities of static network per country

    From: GET /zone/static/cities
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: openapi,openapi-reseller

    Args:
            country: Country
            pool_ip_type: Network type:    `dc`: Datacenter,    `static_res`: ISP

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/zone/static/cities"
    params: dict[str, Any] = {}
    params["country"] = country
    if pool_ip_type is not None:
        params["pool_ip_type"] = pool_ip_type
    return await bd_request("GET", path, params=params)
