"""bd_account_management_list_all_available_countries_per_zone_type — auto-generated tool for GET /countrieslist.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: openapi,openapi-reseller
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "account_management"
WRITES = False


async def bd_account_management_list_all_available_countries_per_zone_type() -> dict[str, Any]:
    """List all available countries per zone type

    From: GET /countrieslist
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: openapi,openapi-reseller

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/countrieslist"
    return await bd_request("GET", path)
