"""bd_account_management_get_zone_bw — auto-generated tool for GET /zone/bw.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: openapi,openapi-reseller
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "account_management"
WRITES = False


async def bd_account_management_get_zone_bw(
    zone: str, from_arg: str | None = None, to: str | None = None
) -> dict[str, Any]:
    """Get the bandwidth stats for a Zone

    From: GET /zone/bw
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: openapi,openapi-reseller

    Args:
            zone: Zone name
            from_arg: Start
            to: End

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/zone/bw"
    params: dict[str, Any] = {}
    params["zone"] = zone
    if from_arg is not None:
        params["from"] = from_arg
    if to is not None:
        params["to"] = to
    return await bd_request("GET", path, params=params)
