"""bd_account_management_get_api_by_partner_name_proxies — auto-generated tool for GET /api/{PARTNER_NAME}/proxies.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: openapi,openapi-reseller
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "account_management"
WRITES = False


async def bd_account_management_get_api_by_partner_name_proxies(
    partner_name: str,
    id: str,
    zone: str | None = None,
    country: str | None = None,
    state: str | None = None,
    session: float | None = None,
    asn: str | None = None,
    carrier: str | None = None,
    const: float | None = None,
    split: float | None = None,
) -> dict[str, Any]:
    """Call GET /api/{PARTNER_NAME}/proxies.

    From: GET /api/{PARTNER_NAME}/proxies
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: openapi,openapi-reseller

    Args:
            partner_name: Name of the proxy zone which will service your request.
            id: Valid customer `id`
            zone: Existing zone name
            country: Name of country (e.g. `us`)
            state: Name of the US country (e.g. `ca`)
            session: Amount of the sessions to generate
            asn: Name of the ASN. YOu can get all available ASNs via `/api/{PARTNER_NAME}/get_asn` API
            carrier: Name of the carrier. You can get all available carriers via `/api/{PARTNER_NAME}/carriers` API
            const: Use constant
            split: If provided only `brd-customer-{CUST_ID}-zone-{ZONE}` part of username will be encoded

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = f"/api/{partner_name}/proxies"
    params: dict[str, Any] = {}
    params["id"] = id
    if zone is not None:
        params["zone"] = zone
    if country is not None:
        params["country"] = country
    if state is not None:
        params["state"] = state
    if session is not None:
        params["session"] = session
    if asn is not None:
        params["asn"] = asn
    if carrier is not None:
        params["carrier"] = carrier
    if const is not None:
        params["const"] = const
    if split is not None:
        params["split"] = split
    return await bd_request("GET", path, params=params)
