"""bd_account_management_create_zone_domain_perm — auto-generated tool for POST /zone/domain_perm.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: openapi,openapi-reseller
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request
from lib.safety import requires_write_enabled

GROUP = "account_management"
WRITES = True


@requires_write_enabled
async def bd_account_management_create_zone_domain_perm(
    body: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Add domain to Zone allowlist or denylist

    From: POST /zone/domain_perm
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: openapi,openapi-reseller

    Args:
            body: JSON request body. See BD docs for schema.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/zone/domain_perm"
    return await bd_request("POST", path, json=body)
