"""bd_account_management_create_zone_ips_refresh — auto-generated tool for POST /zone/ips/refresh.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: openapi,openapi-reseller
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request
from lib.safety import requires_write_enabled

GROUP = "account_management"
WRITES = True


@requires_write_enabled
async def bd_account_management_create_zone_ips_refresh(body: dict[str, Any] | None = None) -> dict[str, Any]:
    """Call POST /zone/ips/refresh.

    From: POST /zone/ips/refresh
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: openapi,openapi-reseller

    Args:
            body: JSON request body. See BD docs for schema.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/zone/ips/refresh"
    return await bd_request("POST", path, json=body)
