"""bd_account_management_get_api_by_partner_name_get_asn — auto-generated tool for GET /api/{PARTNER_NAME}/get_asn.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: openapi,openapi-reseller
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "account_management"
WRITES = False


async def bd_account_management_get_api_by_partner_name_get_asn(partner_name: str) -> dict[str, Any]:
    """Call GET /api/{PARTNER_NAME}/get_asn.

    From: GET /api/{PARTNER_NAME}/get_asn
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: openapi,openapi-reseller

    Args:
            partner_name: Name of the proxy zone which will service your request.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = f"/api/{partner_name}/get_asn"
    return await bd_request("GET", path)
