"""bd_account_management_create_api_by_partner_name_usage_webhook — auto-generated tool for POST /api/{PARTNER_NAME}/usage_webhook.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: openapi,openapi-reseller
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request
from lib.safety import requires_write_enabled

GROUP = "account_management"
WRITES = True


@requires_write_enabled
async def bd_account_management_create_api_by_partner_name_usage_webhook(
    partner_name: str, id: str, zone: str | None = None, body: dict[str, Any] | None = None
) -> dict[str, Any]:
    """Call POST /api/{PARTNER_NAME}/usage_webhook.

    From: POST /api/{PARTNER_NAME}/usage_webhook
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: openapi,openapi-reseller

    Args:
            partner_name: Name of the proxy zone which will service your request.
            id: Valid customer `id`
            zone: Name of existing zone
            body: JSON request body. See BD docs for schema.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = f"/api/{partner_name}/usage_webhook"
    params: dict[str, Any] = {}
    params["id"] = id
    if zone is not None:
        params["zone"] = zone
    return await bd_request("POST", path, params=params, json=body)
