"""bd_account_management_get_api_by_partner_name_customers — auto-generated tool for GET /api/{PARTNER_NAME}/customers.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: openapi,openapi-reseller
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "account_management"
WRITES = False


async def bd_account_management_get_api_by_partner_name_customers(
    partner_name: str,
    active: float | None = None,
    limit: int | None = None,
    page: int | None = None,
) -> dict[str, Any]:
    """Call GET /api/{PARTNER_NAME}/customers.

    From: GET /api/{PARTNER_NAME}/customers
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: openapi,openapi-reseller

    Args:
            partner_name: Name of the proxy zone which will service your request.
            active: can be `0`, `1` or empty.   If `0` - return only not active customers.   If `1` - only active.   If empty - return all.
            limit: max amount of account to return on 1 page
            page: number of the page to return

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = f"/api/{partner_name}/customers"
    params: dict[str, Any] = {}
    if active is not None:
        params["active"] = active
    if limit is not None:
        params["limit"] = limit
    if page is not None:
        params["page"] = page
    return await bd_request("GET", path, params=params)
