"""bd_account_management_update_api_by_partner_name_refresh_ips — auto-generated tool for PUT /api/{PARTNER_NAME}/refresh_ips.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: openapi,openapi-reseller
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request
from lib.safety import requires_write_enabled

GROUP = "account_management"
WRITES = True


@requires_write_enabled
async def bd_account_management_update_api_by_partner_name_refresh_ips(
    partner_name: str, id: str, zone: str | None = None, body: dict[str, Any] | None = None
) -> dict[str, Any]:
    """Call PUT /api/{PARTNER_NAME}/refresh_ips.

    From: PUT /api/{PARTNER_NAME}/refresh_ips
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: openapi,openapi-reseller

    Args:
            partner_name: Name of the proxy zone which will service your request.
            id: Valid customer `id`
            zone: Existing zone name
            body: JSON request body. See BD docs for schema.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = f"/api/{partner_name}/refresh_ips"
    params: dict[str, Any] = {}
    params["id"] = id
    if zone is not None:
        params["zone"] = zone
    return await bd_request("PUT", path, params=params, json=body)
