"""bd_account_management_get_api_by_partner_name_countries — auto-generated tool for GET /api/{PARTNER_NAME}/countries.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: openapi,openapi-reseller
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "account_management"
WRITES = False


async def bd_account_management_get_api_by_partner_name_countries(
    partner_name: str, type: str, more_than: float | None = None, mode: str | None = None
) -> dict[str, Any]:
    """Call GET /api/{PARTNER_NAME}/countries.

    From: GET /api/{PARTNER_NAME}/countries
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: openapi,openapi-reseller

    Args:
            partner_name: Name of the proxy zone which will service your request.
            type: required signup type (`residential`|`shared_dc`|`dedicated_dc`|`shared_isp`|`smart_resi`)
            more_than: minimum amount of free ips on the type
            mode: Flag to change output format. If set to `raw`, the API will return the exact amount of ips per country and `more_than` will be ignored.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = f"/api/{partner_name}/countries"
    params: dict[str, Any] = {}
    params["type"] = type
    if more_than is not None:
        params["more_than"] = more_than
    if mode is not None:
        params["mode"] = mode
    return await bd_request("GET", path, params=params)
