"""bd_account_management_list_zone_count_available_ips — auto-generated tool for GET /zone/count_available_ips.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: openapi,openapi-reseller
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "account_management"
WRITES = False


async def bd_account_management_list_zone_count_available_ips(
    zone: str | None = None, plan: dict[str, Any] | None = None
) -> dict[str, Any]:
    """Call GET /zone/count_available_ips.

    From: GET /zone/count_available_ips
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: openapi,openapi-reseller

    Args:
            zone: name of the Zone
            plan: Query parameter.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/zone/count_available_ips"
    params: dict[str, Any] = {}
    if zone is not None:
        params["zone"] = zone
    if plan is not None:
        params["plan"] = plan
    return await bd_request("GET", path, params=params)
