"""bd_account_management_list_zone_permissions — auto-generated tool for GET /zone/permissions.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: openapi,openapi-reseller
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "account_management"
WRITES = False


async def bd_account_management_list_zone_permissions(zone: str) -> dict[str, Any]:
    """Get Zone permissions

    From: GET /zone/permissions
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: openapi,openapi-reseller

    Args:
            zone: Zone Info

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/zone/permissions"
    params: dict[str, Any] = {}
    params["zone"] = zone
    return await bd_request("GET", path, params=params)
