"""bd_account_management_list_zone_route_ips — auto-generated tool for GET /zone/route_ips.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: openapi,openapi-reseller
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "account_management"
WRITES = False


async def bd_account_management_list_zone_route_ips(zone: str, country: str | None = None, list_countries: bool | None = None) -> dict[str, Any]:
    """Get the available Data center/ISP IPs per Zone

    From: GET /zone/route_ips
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: openapi,openapi-reseller

    Args:
            zone: Zone
            country: 2-letter Country code
            list_countries: Return `JSON` array of `[{ip, country},..]` instead of plain list of IPs

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/zone/route_ips"
    params: dict[str, Any] = {}
    params["zone"] = zone
    if country is not None:
        params["country"] = country
    if list_countries is not None:
        params["list_countries"] = list_countries
    return await bd_request("GET", path, params=params)
