"""bd_account_management_delete_api_by_partner_name_ips — auto-generated tool for DELETE /api/{PARTNER_NAME}/ips.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: openapi,openapi-reseller
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request
from lib.safety import requires_write_enabled

GROUP = "account_management"
WRITES = True


@requires_write_enabled
async def bd_account_management_delete_api_by_partner_name_ips(partner_name: str, id: str, zone: str | None = None) -> dict[str, Any]:
    """Call DELETE /api/{PARTNER_NAME}/ips.

    From: DELETE /api/{PARTNER_NAME}/ips
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: openapi,openapi-reseller

    Args:
            partner_name: Name of the proxy zone which will service your request.
            id: Valid customer `id`
            zone: Existing zone name

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = f"/api/{partner_name}/ips"
    params: dict[str, Any] = {}
    params["id"] = id
    if zone is not None:
        params["zone"] = zone
    return await bd_request("DELETE", path, params=params)
