"""bd_account_management_list_zone_ips — auto-generated tool for GET /zone/ips.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: openapi,openapi-reseller
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "account_management"
WRITES = False


async def bd_account_management_list_zone_ips(zone: str, ip_per_country: str | None = None) -> dict[str, Any]:
    """Get Zone Static (Datacenter/ISP) IPs

    From: GET /zone/ips
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: openapi,openapi-reseller

    Args:
            zone: Zone name
            ip_per_country: get the total amount of IPs per country

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/zone/ips"
    params: dict[str, Any] = {}
    params["zone"] = zone
    if ip_per_country is not None:
        params["ip_per_country"] = ip_per_country
    return await bd_request("GET", path, params=params)
