"""bd_account_management_create_api_by_partner_name_signup_shared_isp — auto-generated tool for POST /api/{PARTNER_NAME}/signup_shared_isp.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: openapi,openapi-reseller
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request
from lib.safety import requires_write_enabled

GROUP = "account_management"
WRITES = True


@requires_write_enabled
async def bd_account_management_create_api_by_partner_name_signup_shared_isp(partner_name: str, zone: str | None = None) -> dict[str, Any]:
    """Call POST /api/{PARTNER_NAME}/signup_shared_isp.

    From: POST /api/{PARTNER_NAME}/signup_shared_isp
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: openapi,openapi-reseller

    Args:
            partner_name: Name of the proxy zone which will service your request.
            zone: Zone name

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = f"/api/{partner_name}/signup_shared_isp"
    params: dict[str, Any] = {}
    if zone is not None:
        params["zone"] = zone
    return await bd_request("POST", path, params=params)
