"""bd_account_management_get_zone_ips_unavailable — auto-generated tool for GET /zone/ips/unavailable.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: openapi,openapi-reseller
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "account_management"
WRITES = False


async def bd_account_management_get_zone_ips_unavailable() -> dict[str, Any]:
    """Get live status of Static (Datacenter/ISP) Zone and IPs with connectivity problem

    From: GET /zone/ips/unavailable
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: openapi,openapi-reseller

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/zone/ips/unavailable"
    return await bd_request("GET", path)
