"""bd_account_management_list_zone_get_active_zones — auto-generated tool for GET /zone/get_active_zones.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: openapi,openapi-reseller
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "account_management"
WRITES = False


async def bd_account_management_list_zone_get_active_zones() -> dict[str, Any]:
    """Return all active zones

    From: GET /zone/get_active_zones
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: openapi,openapi-reseller

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/zone/get_active_zones"
    return await bd_request("GET", path)
