"""bd_account_management_create_zone_remove_password — auto-generated tool for POST /zone/remove_password.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: openapi,openapi-reseller
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request
from lib.safety import requires_write_enabled

GROUP = "account_management"
WRITES = True


@requires_write_enabled
async def bd_account_management_create_zone_remove_password(
    body: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Remove Zone Password

    Remove one or more passwords from a zone. At least one password must remain on the zone
    — this request will fail if it would leave the zone with no passwords.

    From: POST /zone/remove_password
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: openapi,openapi-reseller

    Args:
            body: JSON request body. See BD docs for schema.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/zone/remove_password"
    return await bd_request("POST", path, json=body)
