"""bd_account_management_get_zone_proxies_pending_replacement — auto-generated tool for GET /zone/proxies_pending_replacement.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: openapi,openapi-reseller
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "account_management"
WRITES = False


async def bd_account_management_get_zone_proxies_pending_replacement(
    zone: str | None = None,
) -> dict[str, Any]:
    """Get list of all proxies in the provided zone, which are pending replacement

    From: GET /zone/proxies_pending_replacement
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: openapi,openapi-reseller

    Args:
            zone: Zone

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/zone/proxies_pending_replacement"
    params: dict[str, Any] = {}
    if zone is not None:
        params["zone"] = zone
    return await bd_request("GET", path, params=params)
