"""bd_account_management_create_api_by_partner_name_signup_residential — auto-generated tool for POST /api/{PARTNER_NAME}/signup_residential.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: openapi,openapi-reseller
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request
from lib.safety import requires_write_enabled

GROUP = "account_management"
WRITES = True


@requires_write_enabled
async def bd_account_management_create_api_by_partner_name_signup_residential(partner_name: str, body: dict[str, Any] | None = None) -> dict[str, Any]:
    """Call POST /api/{PARTNER_NAME}/signup_residential.

    From: POST /api/{PARTNER_NAME}/signup_residential
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: openapi,openapi-reseller

    Args:
            partner_name: Name of the proxy zone which will service your request.
            body: JSON request body. See BD docs for schema.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = f"/api/{partner_name}/signup_residential"
    return await bd_request("POST", path, json=body)
