"""bd_account_management_list_status — auto-generated tool for GET /status.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: openapi,openapi-reseller
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "account_management"
WRITES = False


async def bd_account_management_list_status() -> dict[str, Any]:
    """Get account status

    From: GET /status
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: openapi,openapi-reseller

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/status"
    return await bd_request("GET", path)
