"""bd_account_management_list_zone_recent_ips — auto-generated tool for GET /zone/recent_ips.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: openapi,openapi-reseller
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "account_management"
WRITES = False


async def bd_account_management_list_zone_recent_ips(zones: str | None = None) -> dict[str, Any]:
    """Call GET /zone/recent_ips.

    From: GET /zone/recent_ips
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: openapi,openapi-reseller

    Args:
            zones: To get attempting IPs to any of your zone: `zones=*`

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/zone/recent_ips"
    params: dict[str, Any] = {}
    if zones is not None:
        params["zones"] = zones
    return await bd_request("GET", path, params=params)
