"""bd_account_management_get_customer_bw — auto-generated tool for GET /customer/bw.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: openapi,openapi-reseller
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "account_management"
WRITES = False


async def bd_account_management_get_customer_bw(from_arg: str | None = None, to: str | None = None) -> dict[str, Any]:
    """Get the bandwidth stats for all your Zones

    From: GET /customer/bw
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: openapi,openapi-reseller

    Args:
            from_arg: Start
            to: End

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/customer/bw"
    params: dict[str, Any] = {}
    if from_arg is not None:
        params["from"] = from_arg
    if to is not None:
        params["to"] = to
    return await bd_request("GET", path, params=params)
