"""bd_account_management_list_cities — auto-generated tool for GET /cities.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: openapi,openapi-reseller
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "account_management"
WRITES = False


async def bd_account_management_list_cities(country: str) -> dict[str, Any]:
    """Get a list of cities from a Country

    From: GET /cities
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: openapi,openapi-reseller

    Args:
            country: 2-letter `COUNTRY_CODE`

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/cities"
    params: dict[str, Any] = {}
    params["country"] = country
    return await bd_request("GET", path, params=params)
