"""bd_account_management_get_zone_whitelist — auto-generated tool for GET /zone/whitelist.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: openapi,openapi-reseller
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "account_management"
WRITES = False


async def bd_account_management_get_zone_whitelist(zones: str | None = None) -> dict[str, Any]:
    """Get a list of allowlisted IPs for a specific Zone

    From: GET /zone/whitelist
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: openapi,openapi-reseller

    Args:
            zones: A comma-separated list of zone identifiers to filter the request by. If not provided, defaults to '*', indicating all zones.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/zone/whitelist"
    params: dict[str, Any] = {}
    if zones is not None:
        params["zones"] = zones
    return await bd_request("GET", path, params=params)
