"""bd_account_management_update_api_by_partner_name_disable_customer — auto-generated tool for PUT /api/{PARTNER_NAME}/disable_customer.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: openapi,openapi-reseller
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request
from lib.safety import requires_write_enabled

GROUP = "account_management"
WRITES = True


@requires_write_enabled
async def bd_account_management_update_api_by_partner_name_disable_customer(
    partner_name: str, id: str
) -> dict[str, Any]:
    """Call PUT /api/{PARTNER_NAME}/disable_customer.

    From: PUT /api/{PARTNER_NAME}/disable_customer
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: openapi,openapi-reseller

    Args:
            partner_name: Name of the proxy zone which will service your request.
            id: Valid customer `id`

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = f"/api/{partner_name}/disable_customer"
    params: dict[str, Any] = {}
    params["id"] = id
    return await bd_request("PUT", path, params=params)
