"""scraping_shield group — auto-generated tool registrations.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Hand-written smoke tools (with `# SMOKE-TOOL: hand-written` marker) are preserved.
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import TYPE_CHECKING

from .bd_scraping_shield_get_shield_domains_by_class import bd_scraping_shield_get_shield_domains_by_class
from .bd_scraping_shield_get_shield_zones_by_class import bd_scraping_shield_get_shield_zones_by_class
from .bd_scraping_shield_list_shield_class import bd_scraping_shield_list_shield_class
from .bd_scraping_shield_list_shield_samples import bd_scraping_shield_list_shield_samples

if TYPE_CHECKING:
    from fastmcp import FastMCP


def register_tools(mcp: FastMCP) -> None:
    """Register all scraping_shield tools with the FastMCP instance."""
    mcp.tool()(bd_scraping_shield_get_shield_domains_by_class)
    mcp.tool()(bd_scraping_shield_get_shield_zones_by_class)
    mcp.tool()(bd_scraping_shield_list_shield_class)
    mcp.tool()(bd_scraping_shield_list_shield_samples)


__all__ = [
    "bd_scraping_shield_get_shield_domains_by_class",
    "bd_scraping_shield_get_shield_zones_by_class",
    "bd_scraping_shield_list_shield_class",
    "bd_scraping_shield_list_shield_samples",
    "register_tools",
]
