"""bd_scraping_shield_get_shield_zones_by_class — auto-generated tool for GET /shield/zones_by_class.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: scraping-shield-rest-api
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "scraping_shield"
WRITES = False


async def bd_scraping_shield_get_shield_zones_by_class(from_arg: str | None = None, to: str | None = None, cn: str | None = None, peer_cn: str | None = None, categories: str | None = None, order_by: str | None = None, order: str | None = None) -> dict[str, Any]:
    """Returns usage data per zone for the chosen classification

    From: GET /shield/zones_by_class
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: scraping-shield-rest-api

    Args:
            from_arg: start time frame of requested data. Example: `from=2018-07-01T00:00:00`
            to: end time frame of requested data. Example: `to=2018-07-02T00:00:00`
            cn: country of the request origin. Example: `cn=uk`
            peer_cn: country of the peer IP. Example: `peer_cn=us`
            categories: returns only specific classifications. Example: `categories=ads`
            order_by: orders results by bw/requests. `order_by=bw` or `order_by=req`
            order: orders results by size in ascending/descending order. `order=asc` or `order=desc`

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/shield/zones_by_class"
    params: dict[str, Any] = {}
    if from_arg is not None:
        params["from"] = from_arg
    if to is not None:
        params["to"] = to
    if cn is not None:
        params["cn"] = cn
    if peer_cn is not None:
        params["peer_cn"] = peer_cn
    if categories is not None:
        params["categories"] = categories
    if order_by is not None:
        params["order_by"] = order_by
    if order is not None:
        params["order"] = order
    return await bd_request("GET", path, params=params)
