"""deep_lookup group — auto-generated tool registrations.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Hand-written smoke tools (with `# SMOKE-TOOL: hand-written` marker) are preserved.
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import TYPE_CHECKING

from .bd_deep_lookup_create_enhance_query import bd_deep_lookup_create_enhance_query
from .bd_deep_lookup_create_preview import bd_deep_lookup_create_preview
from .bd_deep_lookup_create_request_by_id_cancel import bd_deep_lookup_create_request_by_id_cancel
from .bd_deep_lookup_create_request_by_id_enrich import bd_deep_lookup_create_request_by_id_enrich
from .bd_deep_lookup_create_trigger import bd_deep_lookup_create_trigger
from .bd_deep_lookup_get_preview_by_id import bd_deep_lookup_get_preview_by_id
from .bd_deep_lookup_get_request_by_id import bd_deep_lookup_get_request_by_id
from .bd_deep_lookup_get_request_by_id_download import bd_deep_lookup_get_request_by_id_download
from .bd_deep_lookup_get_request_by_id_status import bd_deep_lookup_get_request_by_id_status

if TYPE_CHECKING:
    from fastmcp import FastMCP


def register_tools(mcp: FastMCP) -> None:
    """Register all deep_lookup tools with the FastMCP instance."""
    mcp.tool()(bd_deep_lookup_create_enhance_query)
    mcp.tool()(bd_deep_lookup_create_preview)
    mcp.tool()(bd_deep_lookup_create_request_by_id_cancel)
    mcp.tool()(bd_deep_lookup_create_request_by_id_enrich)
    mcp.tool()(bd_deep_lookup_create_trigger)
    mcp.tool()(bd_deep_lookup_get_preview_by_id)
    mcp.tool()(bd_deep_lookup_get_request_by_id)
    mcp.tool()(bd_deep_lookup_get_request_by_id_download)
    mcp.tool()(bd_deep_lookup_get_request_by_id_status)


__all__ = [
    "bd_deep_lookup_create_enhance_query",
    "bd_deep_lookup_create_preview",
    "bd_deep_lookup_create_request_by_id_cancel",
    "bd_deep_lookup_create_request_by_id_enrich",
    "bd_deep_lookup_create_trigger",
    "bd_deep_lookup_get_preview_by_id",
    "bd_deep_lookup_get_request_by_id",
    "bd_deep_lookup_get_request_by_id_download",
    "bd_deep_lookup_get_request_by_id_status",
    "register_tools",
]
