"""bd_deep_lookup_get_request_by_id_download — auto-generated tool for GET /request/{id}/download.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: deep-lookup
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "deep_lookup"
WRITES = False


async def bd_deep_lookup_get_request_by_id_download(id: str, format: str | None = None) -> dict[str, Any]:
    """Download Results

    Export results in JSON, CSV, or Excel.

    From: GET /request/{id}/download
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: deep-lookup

    Args:
            id: Path parameter.
            format: **Note:** Excel format is not currently available.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = f"/request/{id}/download"
    params: dict[str, Any] = {}
    if format is not None:
        params["format"] = format
    return await bd_request("GET", path, params=params)
