"""bd_deep_lookup_create_trigger — auto-generated tool for POST /trigger.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: deep-lookup
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request
from lib.safety import requires_write_enabled

GROUP = "deep_lookup"
WRITES = True


@requires_write_enabled
async def bd_deep_lookup_create_trigger(body: dict[str, Any] | None = None) -> dict[str, Any]:
    """Trigger Full Request

    Execute the full research based on preview or with detailed specifications.

    From: POST /trigger
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: deep-lookup

    Args:
            body: JSON request body. See BD docs for schema.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/trigger"
    return await bd_request("POST", path, json=body)
