"""bd_deep_lookup_create_request_by_id_enrich — auto-generated tool for POST /request/{id}/enrich.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: deep-lookup
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request
from lib.safety import requires_write_enabled

GROUP = "deep_lookup"
WRITES = True


@requires_write_enabled
async def bd_deep_lookup_create_request_by_id_enrich(
    id: str, body: dict[str, Any] | None = None
) -> dict[str, Any]:
    """Enrich Column

    Add additional data columns to existing results.

    From: POST /request/{id}/enrich
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: deep-lookup

    Args:
            id: Path parameter.
            body: JSON request body. See BD docs for schema.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = f"/request/{id}/enrich"
    return await bd_request("POST", path, json=body)
