"""bd_deep_lookup_get_preview_by_id — auto-generated tool for GET /preview/{id}.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: deep-lookup
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "deep_lookup"
WRITES = False


async def bd_deep_lookup_get_preview_by_id(id: str) -> dict[str, Any]:
    """Get Preview Data

    Retrieve the preview results and metadata.

    From: GET /preview/{id}
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: deep-lookup

    Args:
            id: Path parameter.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = f"/preview/{id}"
    return await bd_request("GET", path)
