"""bd_deep_lookup_create_preview — auto-generated tool for POST /preview.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: deep-lookup
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request
from lib.safety import requires_write_enabled

GROUP = "deep_lookup"
WRITES = True


@requires_write_enabled
async def bd_deep_lookup_create_preview(body: dict[str, Any] | None = None) -> dict[str, Any]:
    """Create Preview

    Generate a preview to validate your query.

    From: POST /preview
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: deep-lookup

    Args:
            body: JSON request body. See BD docs for schema.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/preview"
    return await bd_request("POST", path, json=body)
