"""bd_deep_lookup_get_request_by_id_status — auto-generated tool for GET /request/{id}/status.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: deep-lookup
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "deep_lookup"
WRITES = False


async def bd_deep_lookup_get_request_by_id_status(id: str) -> dict[str, Any]:
    """Get Request Status

    Check the status of your research request.

    From: GET /request/{id}/status
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: deep-lookup

    Args:
            id: Path parameter.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = f"/request/{id}/status"
    return await bd_request("GET", path)
