"""bd_deep_lookup_create_request_by_id_cancel — auto-generated tool for POST /request/{id}/cancel.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: deep-lookup
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request
from lib.safety import requires_write_enabled

GROUP = "deep_lookup"
WRITES = True


@requires_write_enabled
async def bd_deep_lookup_create_request_by_id_cancel(id: str) -> dict[str, Any]:
    """Cancel Request

    Cancel an in-progress research request.

    From: POST /request/{id}/cancel
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: deep-lookup

    Args:
            id: Path parameter.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = f"/request/{id}/cancel"
    return await bd_request("POST", path)
