"""browser_api group — auto-generated tool registrations.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Hand-written smoke tools (with `# SMOKE-TOOL: hand-written` marker) are preserved.
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import TYPE_CHECKING

from .bd_browser_api_get_browser_sessions_by_session_id import (
    bd_browser_api_get_browser_sessions_by_session_id,
)
from .bd_browser_api_list_browser_sessions import bd_browser_api_list_browser_sessions

if TYPE_CHECKING:
    from fastmcp import FastMCP


def register_tools(mcp: FastMCP) -> None:
    """Register all browser_api tools with the FastMCP instance."""
    mcp.tool()(bd_browser_api_get_browser_sessions_by_session_id)
    mcp.tool()(bd_browser_api_list_browser_sessions)


__all__ = [
    "bd_browser_api_get_browser_sessions_by_session_id",
    "bd_browser_api_list_browser_sessions",
    "register_tools",
]
