"""bd_browser_api_get_browser_sessions_by_session_id — auto-generated tool for GET /browser_sessions/{session_id}.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: browser-api
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "browser_api"
WRITES = False


async def bd_browser_api_get_browser_sessions_by_session_id(session_id: str) -> dict[str, Any]:
    """Get single browser session

    Retrieve details of a specific browser session using its session_id.

    From: GET /browser_sessions/{session_id}
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: browser-api

    Args:
            session_id: Unique session identifier.   > To retrieve the `session_id` of your current browser session, use [`Browser.getSessionId`](https://docs.brightdata.com/scraping-automation/scraping-browser/cdp-functions/custom#getting-session-id) CDP command.

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = f"/browser_sessions/{session_id}"
    return await bd_request("GET", path)
