"""bd_browser_api_list_browser_sessions — auto-generated tool for GET /browser_sessions.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Source spec: browser-api
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import Any

from lib.client import bd_request

GROUP = "browser_api"
WRITES = False


async def bd_browser_api_list_browser_sessions(api_name: str | None = None, limit: int | None = None, offset: int | None = None, status: str | None = None, start_date: str | None = None, end_date: str | None = None, target_url: str | None = None, end_url: str | None = None, sort: str | None = None, order: str | None = None) -> dict[str, Any]:
    """List browser sessions

    Retrieve a list of browser sessions with filtering and pagination.

    From: GET /browser_sessions
    Docs: https://docs.brightdata.com/api-reference/
    Source spec: browser-api

    Args:
            api_name: Name of the Browser API used
            limit: Number of sessions to return
            offset: Pagination offset
            status: Filter by session status
            start_date: Start date filter
            end_date: End date filter
            target_url: Filter by target url (e.g., example.com)
            end_url: Filter by end url (e.g., https://www.example.com/example/sub)
            sort: Sort field: timestamp, duration, bandwidth
            order: Sort order: `asc` or `desc`

    Returns:
        Parsed JSON response, or `{"error": str, "status_code": int, ...}` on failure.
    """
    path = "/browser_sessions"
    params: dict[str, Any] = {}
    if api_name is not None:
        params["api_name"] = api_name
    if limit is not None:
        params["limit"] = limit
    if offset is not None:
        params["offset"] = offset
    if status is not None:
        params["status"] = status
    if start_date is not None:
        params["start_date"] = start_date
    if end_date is not None:
        params["end_date"] = end_date
    if target_url is not None:
        params["target_url"] = target_url
    if end_url is not None:
        params["end_url"] = end_url
    if sort is not None:
        params["sort"] = sort
    if order is not None:
        params["order"] = order
    return await bd_request("GET", path, params=params)
