"""serp group — auto-generated tool registrations.

Auto-generated by lib/codegen.py. DO NOT EDIT BY HAND.
To regenerate: `uv run python scripts/regenerate.py`.

Hand-written smoke tools (with `# SMOKE-TOOL: hand-written` marker) are preserved.
"""
# ruff: noqa
# pyright: ignore

from __future__ import annotations

from typing import TYPE_CHECKING

from .bd_serp_create_request import bd_serp_create_request
from .bd_serp_get_request import bd_serp_get_request
from .bd_serp_get_response import bd_serp_get_response

if TYPE_CHECKING:
    from fastmcp import FastMCP


def register_tools(mcp: FastMCP) -> None:
    """Register all serp tools with the FastMCP instance."""
    mcp.tool()(bd_serp_create_request)
    mcp.tool()(bd_serp_get_request)
    mcp.tool()(bd_serp_get_response)


__all__ = [
    "bd_serp_create_request",
    "bd_serp_get_request",
    "bd_serp_get_response",
    "register_tools",
]
